name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - trunk
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - name: Create environment.ts
        run: |
          mkdir -p src/environments
          echo "export const environment = {" > src/environments/environment.ts
          echo "  firebase: {" >> src/environments/environment.ts
          echo "    projectId: '${{ secrets.PROJECT_ID }}'," >> src/environments/environment.ts
          echo "    appId: '${{ secrets.FIREBASE_APP_ID }}.firebaseapp.com'," >> src/environments/environment.ts
          echo "    storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}'," >> src/environments/environment.ts
          echo "    apiKey: '${{ secrets.FIREBASE_API_KEY }}.appspot.com'," >> src/environments/environment.ts
          echo "    authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}'," >> src/environments/environment.ts
          echo "    messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'," >> src/environments/environment.ts
          echo "    measurementId: '${{ secrets.FIREBASE_MEASUREMENT_ID }}'" >> src/environments/environment.ts
          echo "  }" >> src/environments/environment.ts
          echo "};" >> src/environments/environment.ts
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SD_SERVICEVIEW }}
          channelId: live
          projectId: sd-serviceview
