name: Angular CI

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]
    
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install Dependencies
        run: npm ci
      - name: Build Angular app (dev)
        run: npm run build --
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy --only hosting
          cwd: ${{ github.workspace }}/dist/sd-service-view-app/browser
          firebaseKey: ${{ secrets.FIREBASE_DEPLOY_TOKEN_DEV }}
          projectId: ${{ secrets.PROJECT_ID }}
